// Generated by EmDash on dev server start
// Do not edit manually

/// <reference types="emdash/locals" />

import type { BylineSummary, ContentBylineCredit, TaxonomyTerm, PortableTextBlock } from "emdash";

export interface Page {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  intro?: PortableTextBlock[];
  content?: PortableTextBlock[];
  card?: PortableTextBlock[];
  postscript?: string;
  portrait?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown>; darkVariant?: { id: string; src?: string; alt?: string; width?: number; height?: number; filename?: string; mimeType?: string; blurhash?: string; dominantColor?: string; focalX?: number; focalY?: number; provider?: string; previewUrl?: string; meta?: Record<string, unknown> } };
  template?: "default" | "about" | "newsletter";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface Post {
  id: string;
  slug: string | null;
  status: string;
  title: string;
  excerpt?: string;
  content?: PortableTextBlock[];
  display_date?: string;
  is_podcast?: boolean;
  home_list?: "none" | "start-here" | "most-read";
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

export interface SiteCopy {
  id: string;
  slug: string | null;
  status: string;
  accent_word?: string;
  hero_headline?: string;
  hero_intro?: string;
  email_placeholder?: string;
  submit_label?: string;
  hero_tagline?: string;
  band_intro?: string;
  band_tagline?: string;
  popup_title?: string;
  popup_body?: string;
  popup_button?: string;
  thanks_message?: string;
  footer_line?: string;
  book_label?: string;
  book_url?: string;
  archive_title?: string;
  archive_intro?: string;
  start_heading?: string;
  most_read_heading?: string;
  inline_title?: string;
  inline_body?: string;
  inline_button?: string;
  newsletter_byline?: string;
  book_box_title?: string;
  book_box_link?: string;
  callout_label?: string;
  privacy_label?: string;
  home_intro?: PortableTextBlock[];
  createdAt: Date;
  updatedAt: Date;
  publishedAt: Date | null;
  byline?: BylineSummary | null;
  bylines?: ContentBylineCredit[];
  terms?: Record<string, TaxonomyTerm[]>;
}

declare module "emdash" {
  interface EmDashCollections {
    pages: Page;
    posts: Post;
    site_copy: SiteCopy;
  }
}